socialmedia/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$',auth_views.LoginView.as_view(
                                        template_name='accounts/login.html'),
                                        name='login'),
    # url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'^logout/$',views.logout_view,name='logout')
    url(r'signup/$',views.SignUp.as_view(),name='signup')
]

socialmedia/socialmedia/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from accounts import urls
from . import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'accounts/',include('accounts.urls',namespace='accounts')),
    url(r'accounts/',include('django.contrib.auth.urls')),
    url(r'test/$',views.TestPage.as_view(),name='test'),
    url(r'thanks/$',views.ThanksPage.as_view(),name='thanks')
]

socialmedia/accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return '@{}'.format(self.username)

socialmedia/groups/models.py
from django.db import models

# Create your models here.

socialmedia/posts/models.py
from django.db import models

# Create your models here.

socialmedia/accounts/forms.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username','email','first_name','last_name','password1',
                    'password2')
        model = get_user_model()

socialmedia/accounts/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView
from accounts.forms import UserCreateForm
# Create your views here.

class SignUp(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy("login")
    template_name = 'accounts/signup.html'

socialmedia/groups/views.py
from django.shortcuts import render

# Create your views here.

socialmedia/posts/views.py
from django.shortcuts import render

# Create your views here.

socialmedia/socialmedia/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

socialmedia/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
{% load bootstrap3 %}

  <div class="container">
      <h1>LogIn</h1>
      <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn default" value="LogIn">
      </form>
  </div>


{% endblock %}

socialmedia/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
{% load bootstrap3 %}

  <div class="container">
      <h1>Sign Up</h1>
      <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn default" value="SignUp">
      </form>
  </div>


{% endblock %}

socialmedia/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Social Media</title>

    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/master.css'%}">
  </head>
  <body>

    <nav class="navbar mynav" role='navigation' id='navbar'>
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Social Media</a>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li> <a href="#">Post</a> </li>
          <li> <a href="#">Groups</a> </li>
          <li> <a href="#">Create Group</a> </li>
          <li> <a href="{% url 'accounts:logout' %}">Logout</a> </li>
          {% else %}
    			 <li><a href="#"class="btn btn-simple">Groups</a></li>
		       <li><a href="{% url 'login' %}" class="btn btn-simple">Log in</a></li>
    		   <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    			{% endif %}
        </ul>
      </div>

    </nav>
  {% block content %}
  {% endblock %}

  </body>
</html>

socialmedia/templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to Social Media</h1>

{% endblock %}

socialmedia/templates/test.html
{% extends 'base.html' %}

{% block content %}
<h1>This is test page</h1>
{% endblock %}

socialmedia/templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks for visiting</h1>
{% endblock %}